# Generated by Django 4.2.3 on 2023-08-24 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=300)),
                ('image', models.ImageField(upload_to='personal_portfolio/images')),
                ('url', models.URLField(blank=True)),
            ],
        ),
    ]
